### ISSUE TITLE
Support for azapi_resource instead of azurerm_storage_share

### ISSUE THREAD

**Issue by stredovek** [Azure/terraform-azurerm-avm-res-storage-storageaccount#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Is it possible implement  what is in place for containers also for file shares? `azurerm_storage_share`  works but requires public access to storage account all the time. `azapi_resource` does not have such dependency.  Private endpoints cannot help here  in the case terraform code is executed from internet location. Once `public_network_access_enabled=false` is set in   `azurerm_storage_account` , the error (403 This request is not authorized to perform this operation) is reported as expected.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_share, azurerm_storage_account

**Comment by chinthakaru** [comment]
@stredovek We have released the AzApi version for all the Sub-resources and these issues should be rectified now.
