### ISSUE TITLE
[AVM Module Issue]: Permission issue and request timeout

### ISSUE THREAD

**Issue by jerryshia** [Azure/terraform-azurerm-avm-res-storage-storageaccount#113]
1.
**Describe the issue:**
When test the example [customer-managed-key](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/customer-managed-key) of module `avm-res-storage-storageaccount`, it returns AuthorizationFail.

![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/139106314/f429e330-461a-4142-a3b1-21097adbb855)

If we change the `default_action` in the `network_rules` under the `module "this"` to `ALLOW`, it will run successfully.

![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/139106314/b7b304c2-2028-42aa-98bd-fc83f1acf530)

**Module Version:** 0.1.3
**Examples:**`customer-managed-key`,`diagnostic-settings`,`role_assignments`, `private-endpoint`,`private-endpoint-Staticip`

**Repro Steps:**
1. Execute commands: `azd login`, `az login`.
2. Clone terraform template code. E.g:`todo-python-mongo-terraform`
3. Copy and paste the example [customer-managed-key](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/customer-managed-key) into `main.tf`.
4. Annotate the contents of the `infra/output.tf` file.
5. Run `azd provision`.

**Expected behavior:**
Test the example [customer-managed-key](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/customer-managed-key) successfully.

2.
**Describe the issue:**
In the example [private-endpoint](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/private-endpoint) and [private-endpoint-Staticip](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/private-endpoint-Staticip), after modifying the parameter `default_action` to "ALLOW" and running `azd provision`, the program gets stuck when creating the storage queue and file share, and eventually fails to run due to a request timeout.

![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/139106314/0f8a6901-d3a9-4cc7-b578-3833e6c9969e)
![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/139106314/9b67c49d-aba7-426b-bb18-094122ee00fa)

 However, if the VPN is disconnected while creating the storage queue and file share, it ultimately runs successfully.

![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/139106314/ae6b86c4-e156-482f-ad69-4c38247279ee)

**Module Version:** 0.1.3
**Examples:** `private-endpoint`,`private-endpoint-Staticip`

**Repro Steps:**
1. Execute commands: `azd login`, `az login`.
2. Clone terraform template code. E.g:`todo-python-mongo-terraform`
3. Copy and paste the example [private-endpoint](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/private-endpoint)  into `main.tf`.
4. Annotate the contents of the `infra/output.tf` file.
5. Run `azd provision`.

**Expected behavior:**
Test the examples [private-endpoint](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/private-endpoint) and [private-endpoint-Staticip](https://registry.terraform.io/modules/Azure/avm-res-storage-storageaccount/azurerm/latest/examples/private-endpoint-Staticip) successfully.

@matt-FFFFFF, @jaredfholgate and @jongio for notification.

**Comment by jaredfholgate** [comment]
@jerryshia This is a known issue. @chinthakaru is migrating to AzAPI to resolve this. We'll get a release out ASAP.

PR is here: https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/110

**Comment by chinthakaru** [comment]
@jerryshia We have released the AzApi version of sub resources. Please can you test it again?

**Comment by jerryshia** [comment]
@chinthakaru Ok, I will test it again.

**Comment by jerryshia** [comment]
This issue has been resolved. I will close it.
