### ISSUE TITLE
Should this repository be cloned from AVM template?

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-storage-storageaccount#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behaviour

From the AVM guidance (https://azure.github.io/Azure-Verified-Modules/contributing/terraform/#template-repository) recommends using the following template as the starting point:

https://github.com/Azure/terraform-azurerm-avm-template

I've noted that this repository aligns to the previous "terraform verified modules" and thus there are some changes require set the types and use a slightly different CI approach.

### Actual Behaviour

Unsure - is the plan to make changes to this repo, or should it be re-created from the AVM template?

### References

https://azure.github.io/Azure-Verified-Modules/contributing/terraform/#template-repository

**Comment by kewalaka** [comment]
hi @chinthakaru - do you have any feedback on this?  As per the issue on the AVM project here:

https://github.com/Azure/Azure-Verified-Modules/issues/35#issuecomment-1817384117

Quoting my feedback on this issue:

> ok cool. I've got a little present for you all - based on the initial work from @lonegunmanb i've refactored things into an AVM style here (clone off the right template):
> 
> https://github.com/kewalaka/terraform-azurerm-avm-res-storage-storageaccount
> 
> it's still work in progress, the AVM interfaces are implemented. Some basic E2E tests are passing though (default settings + a storage acc + container with access keys disabled, private endpoints), my plan is to re-introduce the complete example once I've got a bit more confidence.
>

**Comment by matt-FFFFFF** [comment]
As discussed, this was a special case and we will remediate required changes to AVM here: https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/tree/avm-sa
