### ISSUE TITLE
Add support for mandatory private endpoints

### ISSUE THREAD

**Issue by on4tux** [Azure/terraform-azurerm-avm-res-storage-storageaccount#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In our company, users need to create private endpoint on Storage Account to be able to access it. This PE needs to exist and have its dns zone propagated before you can create subresources like a container. A workaround is to wait 5 mins after PE creation but other solutions might be possible as well.

### New or Affected Resource(s)/Data Source(s)

time_sleep

### Potential Terraform Configuration

```hcl
resource "time_sleep" "wait_5_min_containers" {
  create_duration = "5m"

  depends_on = [azurerm_private_endpoint.this]
}
```

**Comment by lonegunmanb** [comment]
@on4tux Thanks for opening this issue, would we declare this `time_sleep` resource outside this module, and list the module instance in it's `depends_on` list? For this [example](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/tree/main/examples/private-endpoint), we can add such a `time_sleep` in it's `main.tf` file:

```hcl
resource "time_sleep" "wait_5_min_containers" {
  create_duration = "5m"

  depends_on = [module.this]
}
```

**Comment by chinthakaru** [comment]
@on4tux As suggested by @lonegunmanb, you could incorporate `time_sleep` into `main.tf` within the examples. At present, there are no plans to integrate a timer into the module.
