### ISSUE TITLE
BUG - enable https traffic only is being deprecated

### ISSUE THREAD

**Issue by cshea-msft** [Azure/terraform-azurerm-avm-res-storage-storageaccount#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.3

### Module Version

0.2.1

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_storage account

### Terraform Configuration Files

```hcl
run storage avm module
```

### tfvars variables values

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Actual Behaviour

╷
│ Warning: Argument is deprecated
│
│   with module.storage.azurerm_storage_account.this,
│   on .terraform\modules\storage\main.tf line 17, in resource "azurerm_storage_account" "this":
│   17:   enable_https_traffic_only         = var.enable_https_traffic_only
│
│ The property `enable_https_traffic_only` has been superseded by `https_traffic_only_enabled` and will be removed in v4.0 of the AzureRM Provider.
│
│ (and one more similar warning elsewhere)

**Comment by chinthakaru** [comment]
@cshea-msft Thanks for the notifying this. This has been fixed with the above mentioned PR.
