### ISSUE TITLE
[AVM Module Issue]: Add support for ignore_change private_dns_zone_group

### ISSUE THREAD

**Issue by RelaxingLoki475** [Azure/terraform-azurerm-avm-res-storage-storageaccount#138]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.2.1

### Description

On private endpoint module definition is not managed the case of private_dns_zone_group is not present and then lifecycle ignore_changes for example as module https://github.com/Azure/terraform-azurerm-avm-res-web-site/blob/v0.9.0/main.private_endpoints.tf

**Comment by chinthakaru** [comment]
@RelaxingLoki475 Thank you for reaching out. Are you encountering any errors during the deployment?

**Comment by RelaxingLoki475** [comment]
In our case the private_dns_zone_group configuration is managed centrally by landing zone. When a private endpoint is deployed it is automatically linked to a private_dns_zone_group. In subsequent applies after the first deployment, Terraform identifies this change as unmanaged and discards it in every apply

**Comment by chinthakaru** [comment]
@RelaxingLoki475 Thank you for the feedback. We will update the variable with `private_endpoints_manage_dns_zone_group` within a few days.
