### ISSUE TITLE
[AVM Module Issue]: property `enable_https_traffic_only` has been superseded by `https_traffic_only_enabled` for the resource azurerm_storage_account

### ISSUE THREAD

**Issue by Sakthidasakalathi** [Azure/terraform-azurerm-avm-res-storage-storageaccount#139]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.2.1

### Description

Warning: Argument is deprecated
│
│   with module.webapp_storage_account.azurerm_storage_account.this,
│   on .terraform\modules\webapp_storage_account\main.tf line 17, in resource "azurerm_storage_account" "this":
│   17:   enable_https_traffic_only         = var.enable_https_traffic_only
│
│ The property `enable_https_traffic_only` has been superseded by `https_traffic_only_enabled` and will be removed in v4.0 of the AzureRM Provider.

**Comment by chinthakaru** [comment]
@Sakthidasakalathi Thank you for reaching out. The issue was resolved last week and has been merged with the main branch.

**Comment by Sakthidasakalathi** [comment]
@chinthakaru I see the updates on the main branch, but still terraform init pulls the older bugged configuration files with the tag v0.2.1. I trust a new version tagging will resolve this issue, I'm not sure if I'm missing anything on my end.  

Tried below configuration to call the module, with and without version, but the init pulls only the older files.

module "module_name" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"

module "module_name" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.2.1"

**Comment by chinthakaru** [comment]
@Sakthidasakalathi All the changes have been synced and made a new release. Please can you test this again ?

**Comment by Sakthidasakalathi** [comment]
@chinthakaru, Thank you.! All looks good.

**Comment by chinthakaru** [comment]
@Sakthidasakalathi thanks for the update. let me close the issue.
