### ISSUE TITLE
[AVM Module Issue]: private key issue

### ISSUE THREAD

**Issue by cshea-msft** [Azure/terraform-azurerm-avm-res-storage-storageaccount#140]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.1

### Description

PS C:\Users\chashea\repos\IaC\Terraform\backend> terraform validate     
╷
│ Error: Value for unconfigurable attribute
│
│   with module.stg.azurerm_role_assignment.private_endpoint,
│   on .terraform\modules\stg\main.privateendpoint.tf line 53, in resource "azurerm_role_assignment" "private_endpoint":
│   53:   principal_type                         = each.value.role_assignment.principal_type
│
│ Can't configure a value for "principal_type": its value will be decided automatically based on the      
│ result of applying this configuration.

module "stg" {
  source              = "Azure/avm-res-storage-storageaccount/azurerm"
  version             = "0.2.1"
  name                = "stgterraformbackend"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  account_tier        = "Standard"
  account_replication_type = "LRS"
  containers = {
    container1 = {
      name = "tfstate"
      container_access_type = "private"
    }
  }
}

ran terraform validate and got the error. the validation passed when changed version to 0.1.0

**Comment by lonegunmanb** [comment]
Hi @cshea-msft , could you verify whether your config could generate a valid plan by running `terraform plan` command?

**Comment by cshea-msft** [comment]
@lonegunmanb we can close this. error doesnt show up now. not sure what happened. it was the only module i was deploying. Will close.
