### ISSUE TITLE
[AVM Module Issue]: "An argument named "https_traffic_only_enabled" is not expected here."

### ISSUE THREAD

**Issue by captainhook** [Azure/terraform-azurerm-avm-res-storage-storageaccount#141]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.2

### Description

I am getting the following error since 0.2.2:
```
│ Error: Unsupported argument
│
│   on .terraform\modules\storage-prod\main.tf line 14, in resource "azurerm_storage_account" "this":
│   14:   https_traffic_only_enabled        = var.https_traffic_only_enabled
│
│ An argument named "https_traffic_only_enabled" is not expected here.
```

Is anyone else seeing this on 0.2.2?

**Comment by chinthakaru** [comment]
@captainhook Thanks for reaching out. What is your AzureRM provider version? This flag has been changed since V 3.114.0.

**Comment by captainhook** [comment]
@chinthakaru apologies, that's one of the first things I should have checked :) All ok on 3.114.0!

**Comment by itoffshore** [comment]
I hit this issue too - I think a good practice is:

* pin `azurerm` to a major version (e.g `3.0`)
* set your `TF_CLI_ARGS_init` to also include `-upgrade=true` (so you can fix deprecations as & when they occur automatically)
