### ISSUE TITLE
The body property of the azapi resource must be string

### ISSUE THREAD

**Issue by thenewnano** [Azure/terraform-azurerm-avm-res-storage-storageaccount#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.9.4

### Module Version

0.2.2

### AzureRM Provider Version

3.115.0 

### Affected Resource(s)/Data Source(s)

azapi_resource

### Terraform Configuration Files

```hcl
-
```

### tfvars variables values

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Not see that error

### Actual Behaviour

The minimum version of azapi provider is set to 0.9.0 is not compatible with current code, 0.14.0 works fine, 
You need to use jsonencode() for body if working with 0.9.0 or bump the version

### Steps to Reproduce

instead pf >= use = for the version of Azure/azapi

**Comment by chinthakaru** [comment]
@thenewnano, thank you for the validation. All the necessary changes have been made.
