### ISSUE TITLE
unexpected status 

### ISSUE THREAD

**Issue by cshea-msft** [Azure/terraform-azurerm-avm-res-storage-storageaccount#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3

### Module Version

0.2.3

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_storageaccount

### Terraform Configuration Files

```hcl
module "avm-res-storage-storageaccount" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.2.3"
  name                     = module.naming.storage_account.name_unique
  resource_group_name      = azurerm_resource_group.rg_stg.name
  location                 = azurerm_resource_group.rg_stg.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
  account_kind = "StorageV2"
  public_network_access_enabled = false
  shared_access_key_enabled = false
  default_to_oauth_authentication = true
}
```

### tfvars variables values

```hcl
n/a
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Complete deployment

### Actual Behaviour

│ Error: retrieving queue properties for Storage Account (Subscription: "0ec38a31-9a35-44fe-ac59-8347ac564cef"
│ Resource Group Name: "rg-g22j-stg"
│ Storage Account Name: "stg22j"): executing request: unexpected status 403 (403 Key based authentication is not permitted on this storage account.) with KeyBasedAuthenticationNotPermitted: Key based authentication is not permitted on this storage account.
│ RequestId:99df95d0-e003-0081-1294-f4c575000000
│ Time:2024-08-22T13:09:57.5874197Z
│
│   with module.avm-res-storage-storageaccount.azurerm_storage_account.this,
│   on .terraform\modules\avm-res-storage-storageaccount\main.tf line 1, in resource "azurerm_storage_account" "this":
│    1: resource "azurerm_storage_account" "this" {
│

### Steps to Reproduce

Run storage account module without PE and with public network access set to false

**Comment by cshea-msft** [comment]
closing this and making a feature request

**Comment by holmanjd** [comment]
The default values for this module appear to produce an error as noted above:
Code used in our instance was:
`module "avm-res-storage-storageaccount-tfstate" {
  source                   = "Azure/avm-res-storage-storageaccount/azurerm"
  version                  = "0.2.7"
  name                     = format("%.24s", lower(replace("${local.resource_name_prefix}sttfstate", "/[[:^alnum:]]/", "")))
  resource_group_name      = module.avm-res-resources-resourcegroup-tfstate.resource.name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
  blob_properties = {
    versioning_enabled = true
  }
}`

working code:
`resource "azurerm_storage_account" "tfstate" {
  name                     = format("%.24s", lower(replace("${local.resource_name_prefix}sttfstate", "/[[:^alnum:]]/", "")))
  resource_group_name      = azurerm_resource_group.tfstate.name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
  blob_properties {
    versioning_enabled = true
  }
}
`

Error presented:

│ Error: retrieving queue properties for Storage Account (Subscription: "xxxx7634"
│ Resource Group Name: "xxx-tfstate"
│ Storage Account Name: "xxxtfstate"): executing request: unexpected status 403 (403 Key based authentication is not permitted on this storage account.) with KeyBasedAuthenticationNotPermitted: Key based authentication is not permitted on this storage account.
│ RequestId:  0fbde9000000
│ Time:2024-09-25T17:41:10.2318372Z
│
│   with module.avm-res-storage-storageaccount-tfstate.azurerm_storage_account.this,
│   on .terraform\modules\avm-res-storage-storageaccount-tfstate\main.tf line 1, in resource "azurerm_storage_account" "this":
│    1: resource "azurerm_storage_account" "this" {
│
