### ISSUE TITLE
Support for default_share_level_permission in  azure_files_authentication Variable

### ISSUE THREAD

**Issue by M-Eslam** [Azure/terraform-azurerm-avm-res-storage-storageaccount#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When enabling the `azure_files_authentication` variable, currently the `default_share_level_permission` will have only the default option which is `None` because it's not there in the module TF SA resource. 

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

**Comment by chinthakaru** [comment]
@M-Eslam, thank you for reaching out. The feature has been included in version 3.115.0. I will implement this early next week.

**Comment by chinthakaru** [comment]
The @M-Eslam feature has been released.
