### ISSUE TITLE
Publish to registry

### ISSUE THREAD

**Issue by Israphel** [Azure/terraform-azurerm-avm-res-storage-storageaccount#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Is this going to be published next to the other Azure modules?

I tried with

```terraform
source   = "Azure/avm-res-storage-storageaccount/azurerm"
version  = "0.1.0"
```

but it doesn't seem to be available

**Comment by deejiw** [comment]
Try

`source = "git::github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount?ref=v0.1.0"`

**Comment by matt-FFFFFF** [comment]
This is still in development, we will publish a 0.1.0 version when we are ready
