### ISSUE TITLE
[AVM Module Issue]: removed block is supported in <1.7 versions

### ISSUE THREAD

**Issue by amirkhonov** [Azure/terraform-azurerm-avm-res-storage-storageaccount#160]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

1.2.5

### Description

The `removed` block feature was released in the version v1.7.

`main.deprecated.tf`:
```hcl
removed {
  from = azurerm_storage_account_network_rules.this
  lifecycle {
    destroy = false
  }
}
```

This prerequisite doesn't work:
```
The following requirements are needed by this module:

 terraform (>= 1.3.0)
```

**Comment by chinthakaru** [comment]
@amirkhonov All the changes have been updated and released an version.
