### ISSUE TITLE
ignore private_link_access changes made via defender Azure Policy

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-storage-storageaccount#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.9.5

### Module Version

0.2.7

### AzureRM Provider Version

3.97

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
n/a
```

### tfvars variables values

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

When using Policy to set up Defender malware scanning for storage accounts, Azure Policy adds settings to network_rules -> private_link_access, notably these:

```terraform
private_link_access {
   endpoint_resource_id = "/subscription/<subid>/providers/Microsoft.Security/datascanners/storageDataScanner"
   endpoint_tenant_id = "<tenantid>"
}
```

Ideally the module will set these via a flag 'enabled defender scanning', or ignore these changes, it is noted that ignore_changes needs to be static & can't be dynamically set.

### Actual Behaviour

The module removes these as they were set by Policy, not by Terraform - i.e. similar to the issue with private dns zone groups.

### Steps to Reproduce

Use the module against a storage account with Defender malware scanning enabled

**Comment by lonegunmanb** [comment]
Hi @kewalaka thanks for opening this issue to us. Different users might have different Azure Policy with redemption so the potential requirements for `ignore_chanage` list is limitless.

I have developed a meta-programming tool for Terraform named [`mapotf`](https://github.com/Azure/mapotf), which could help you I believe. Here's a [sample](https://github.com/Azure/mapotf/blob/main/example/customize_aks_ignore_changes/main.mptf.hcl) how to customize `ignore_change` list. `mapotf` acts like `terragrunt`, you can run `mapotf apply -r .... --mptf-dir <your_mptf_dir>`, it will analyze and transform all Terraform configs to your Terraform config files, along with all module config files that referred by your code.

**Comment by kewalaka** [comment]
thanks, i suspected that would be the answer.  As an aside, it only seems to be storage accounts that are set up for Azure Site Recovery.  These exhibit a strange behaviour where they need to be public yet want to set these private link endpoint settings.  We've worked around it by setting these explicitly for storage accounts used for ASR - in this case it seems to work and doesn't stop ASR from being activated.
