### ISSUE TITLE
Support for v2.0 of the azapi provider

### ISSUE THREAD

**Issue by paul-e-martin** [Azure/terraform-azurerm-avm-res-storage-storageaccount#180]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Support for v2.0 of the azapi provider

### New or Affected Resource(s)/Data Source(s)

azapi

**Comment by chinthakaru** [comment]
@paul-e-martin thanks for reaching out. This module is already supports v2. I will make the changes soon.

**Comment by paul-e-martin** [comment]
Hi, thanks, any idea when the support for v2 will be made available?

**Comment by chinthakaru** [comment]
@paul-e-martin This has been updated and released a new version.
