### ISSUE TITLE
KeyBasedAuthenticationNotPermitted: Key based authentication is not permitted on this storage account.

### ISSUE THREAD

**Issue by ankurvc** [Azure/terraform-azurerm-avm-res-storage-storageaccount#184]
I got this issue during apply of module. However its working while I create by my own.. But calling this module is throwing below

Storage Account Name: "storageaccname") to become available: waiting for the Blob Service to become available: polling failed: executing request: unexpected status 403 (403 Key based authentication is not permitted on this storage account.) with KeyBasedAuthenticationNotPermitted: Key based authentication is not permitted on this storage account.

**Comment by pieter-jangoeman** [comment]
Do you want to use key's or not?

**Comment by chinthakaru** [comment]
@ankurvc as explain in the previous reply, you need to set `storage_use_azuread   = true`  within the `AzureRM` provider block.

#RR

**Comment by chinthakaru** [comment]
@ankurvc  as explain in the previous reply, you need to set storage_use_azuread   = true within the AzureRM provider block.

If you have any further issues. Please open a new GH Issue.
