### ISSUE TITLE
Unsupported attribute in output.tf

### ISSUE THREAD

**Issue by madhurshukla23** [Azure/terraform-azurerm-avm-res-storage-storageaccount#188]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.2.8

### Module Version

0.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

output "containers"

### Terraform Configuration Files

```hcl
output "containers" {
  description = "Map of storage containers that are created."
  value = {
    for name, container in azapi_resource.containers :
    name => {
      id            = container.id
      name          = container.name
      public_access = container.body.properties.publicAccess
    }
  }
}
```

### tfvars variables values

```hcl
containers = {
      blob_container0 = {
        name = "preprod"
        #public_access = "container"
      }
      blob_container1 = {
        name = "prod"
        #public_access = "container"
      }
    }
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported attribute
│
│   on .terraform/modules/storage_account/terraform-azurerm-avm-res-storage-storageaccount-main/outputs.tf line 8, in output "containers":
│    8:       public_access = container.body.properties.publicAccess
│     ├────────────────
│     │ container.body is "{\"properties\":{\"immutableStorageWithVersioning\":null,\"metadata\":{},\"publicAccess\":\"container\"}}"
│
│ Can't access attributes on a primitive-typed value (string).
```

### Expected Behaviour

To fix this, rewrite container output to:

output "containers" {
  description = "Map of storage containers that are created."
  value = {
    for name, container in azapi_resource.containers :
    name => {
      id            = container.id
      name          = container.name
      public_access = jsondecode(container.body).properties.publicAccess
    }
  }
}

**Comment by chinthakaru** [comment]
@madhurshukla23 Thanks for reaching out. I believe it doesn't require export inputs. Therefore, `name` and `public_access` will be removed soon.

**Comment by chinthakaru** [comment]
`public_access` and `name` have been removed from the output file. If you have any questions, please do open a GH issue.
