### ISSUE TITLE
Support for alignment to Azure Verified Module specification

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-storage-storageaccount#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is in support of a PR in branch avm-sa, which is tracking alignment to the AVM spec.  

### New or Affected Resource(s)/Data Source(s)

n/a

**Comment by matt-FFFFFF** [comment]
We understand you eagerness to help here but please leave this to us to continue the work.

There is no SLA but we will will release and publish 0.1.0 of the module when we are ready.

**Comment by matt-FFFFFF** [comment]
Merged #26
