### ISSUE TITLE
Deployment error when only specifying required parameters

### ISSUE THREAD

**Issue by bryansan-msft** [Azure/terraform-azurerm-avm-res-storage-storageaccount#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.6.0

### Module Version

0.1.1

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.71"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

module "regions" {
  source  = "Azure/regions/azurerm"
  version = ">= 0.3.0"
}

resource "random_integer" "region_index" {
  max = length(module.regions.regions) - 1
  min = 0
}

module "naming" {
  source  = "Azure/naming/azurerm"
  version = ">= 0.3.0"
}

resource "azurerm_resource_group" "example" {
  name     = module.naming.resource_group.name_unique
  location = module.regions.regions[random_integer.region_index.result].name
}

module "storage_account" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.1.1"

  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  name                = module.naming.storage_account.name_unique
}
```

### tfvars variables values

```hcl
Nothing in tfvars
```

### Debug Output/Panic Output

```shell
│ Error: retrieving queue properties for Storage Account (Subscription: "5c8eb76d-1529-4444-8a2d-cce3e8b22be5"
│ Resource Group Name: "rg-rdb0"
│ Storage Account Name: "strdb0"): unmarshalling response: could not parse response body
│
│   with module.storage_account.azurerm_storage_account.this,
│   on .terraform\modules\storage_account\main.tf line 6, in resource "azurerm_storage_account" "this":
│    6: resource "azurerm_storage_account" "this" {
```

### Expected Behaviour

Deploys an empty storage account successfully 

### Actual Behaviour

Throws an error even though the storage account was created

### Steps to Reproduce

terraform init and apply

### Important Factoids

No

### References

No

**Comment by elacheche** [comment]
I think it's duplicated [at least is related] to #63

**Comment by bryansan-msft** [comment]
It is, but at least here you have a super simple sample to repro the error. So, it is clearly not related to NFS

**Comment by chinthakaru** [comment]
@bryansan-msft Please can you add `storage_use_azuread = true` within the azurerm configuration and test it out ?

**Comment by chinthakaru** [comment]
@winguy2211 Please share your minimum sample code to reproduse the issue.

**Comment by elacheche** [comment]
> @bryansan-msft Please can you add `storage_use_azuread = true` within the azurerm configuration and test it out ?

I tried this with my code from #63 , and I got the same error.

**Comment by dstreitberg** [comment]
I have the same error message. But only if want to disable the shared access keys:
`shared_access_key_enabled = false`
If the keys are enabled, everything works correctly.

**Comment by winguy2211** [comment]
> @winguy2211 Please share your minimum sample code to reproduse the issue.

Here is the code:
terraform {
  required_version = "~> 1.7.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.78.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
  skip_provider_registration = true
  storage_use_azuread        = true
}


# This ensures we have unique CAF compliant names for resources.
module "naming" {
  source  = "Azure/naming/azurerm"
  version = "0.4.0"
}

resource "random_string" "this" {
  length  = 6
  special = false
  upper   = false
}


resource "azurerm_resource_group" "rg_backup" {
  location = var.location
  name     = "${module.naming.resource_group.name}-backup"
}

# We need this to get the object_id of the current user
data "azurerm_client_config" "current" {}

resource "azurerm_user_assigned_identity" "example_identity" {
  location            = azurerm_resource_group.rg_backup.location
  name                = module.naming.user_assigned_identity.name_unique
  resource_group_name = azurerm_resource_group.rg_backup.name
}
# We use the role definition data source to get the id of the Contributor role
data "azurerm_role_definition" "example" {
  name = "Contributor"
}

module "backup_storage_account" {

  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.1.1"

# Change replcation type if needed. 
  account_replication_type      = "LRS"
  account_tier                  = "Standard"
  account_kind                  = "StorageV2"
  location                      = azurerm_resource_group.rg_backup.location
  name                          = module.naming.storage_account.name_unique
  resource_group_name           = azurerm_resource_group.rg_backup.name
  min_tls_version               = "TLS1_2"
  shared_access_key_enabled     = true
  public_network_access_enabled = true
  managed_identities = {
    system_assigned            = true
    user_assigned_resource_ids = [azurerm_user_assigned_identity.example_identity.id]
  }
  tags = var.tags

  #Locks for storage account
  lock = {
    name = "lock"
    kind = "None"
  } 
  role_assignments = {
    role_assignment_1 = {
      role_definition_id_or_name       = data.azurerm_role_definition.example.id
      principal_id                     = data.azurerm_client_config.current.object_id
      skip_service_principal_aad_check = false
    },
    role_assignment_2 = {
      role_definition_id_or_name       = "Owner"
      principal_id                     = data.azurerm_client_config.current.object_id
      skip_service_principal_aad_check = false
    },

  }
  network_rules = {
    bypass                     = ["AzureServices"]
    default_action             = "Deny"
    ip_rules                   = [try(module.public_ip[0].public_ip, var.bypass_ip_cidr)] 
    virtual_network_subnet_ids = toset([azurerm_subnet.private.id])
  }
  containers = {
    blob_container0 = {
      name                  = "backup"
      container_access_type = "private"
      role_assignments = {
        rbac_storage_blob_data_contributor = {
          role_definition_id_or_name = "Storage Blob Data Contributor"
          principal_id               = data.azurerm_client_config.current.object_id
        }
      }
    }
    blob_container1 = {
      name                  = var.backup_container_name
      container_access_type = "private"
      role_assignments = {
        rbac_storage_blob_data_reader = {
          role_definition_id_or_name = "Storage Blob Data Reader"
          principal_id               = data.azurerm_client_config.current.object_id
        }
      }
    }
  }
   depends_on = [
    azurerm_resource_group.rg_backup
  ]
}

output "names" {
  value = {
    rg_name = azurerm_resource_group.rg_backup.name
    backup_storage_account = module.backup_storage_account.name
    vnet_name = azurerm_virtual_network.vnet.name
    subnet_name = azurerm_subnet.private.name
  }
}

module "public_ip" {
  count = var.bypass_ip_cidr == null ? 1 : 0

  source  = "lonegunmanb/public-ip/lonegunmanb"
  version = "0.1.0"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["192.168.0.0/16"]
  location            = azurerm_resource_group.rg_backup.location
  name                = module.naming.virtual_network.name_unique
  resource_group_name = azurerm_resource_group.rg_backup.name
  depends_on = [
    azurerm_resource_group.rg_backup
  ]
}

resource "azurerm_subnet" "private" {
  address_prefixes     = ["192.168.0.0/24"]
  name                 = module.naming.subnet.name_unique
  resource_group_name  = azurerm_resource_group.rg_backup.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  service_endpoints    = ["Microsoft.Storage"]
}

resource "azurerm_network_security_group" "nsg" {
  location            = azurerm_resource_group.rg_backup.location
  name                = module.naming.network_security_group.name_unique
  resource_group_name = azurerm_resource_group.rg_backup.name
}

resource "azurerm_subnet_network_security_group_association" "private" {
  network_security_group_id = azurerm_network_security_group.nsg.id
  subnet_id                 = azurerm_subnet.private.id
}

resource "azurerm_network_security_rule" "no_internet" {
  access                      = "Deny"
  direction                   = "Outbound"
  name                        = module.naming.network_security_rule.name_unique
  network_security_group_name = azurerm_network_security_group.nsg.name
  priority                    = 100
  protocol                    = "*"
  resource_group_name         = azurerm_resource_group.rg_backup.name
  destination_address_prefix  = "Internet"
  destination_port_range      = "*"
  source_address_prefix       = azurerm_subnet.private.address_prefixes[0]
  source_port_range           = "*"
}

**Comment by Artlvns** [comment]
Same issue here with this minimal code.  Tried to remove ```containers``` block and have only 3 mandatory variables, same result. 
```
module "test_storage" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.1.1"

  name                     = local.storage_name
  resource_group_name      = azurerm_resource_group.test.name
  account_replication_type = "LRS"

  containers = {
    scripts = {
      name                  = test_scripts
      container_access_type = "private"
    }
  }

}
```

**Comment by bryansan-msft** [comment]
The problem here is that the module uses EntraId authentication by default. 

It has the parameter "shared_access_key_enabled = false" by default so it is expecting you to specify in the AzureRM provider configuration "storage_use_azuread = true" and have the correct role assignments. Thus, creating this situation. Changing to "shared_access_key_enabled = true" works in case of not wanting to use EntraId authentication.

I asked @chinthakaru to provide a better clarification of this behavior on the documentation as it is a behavior difficult to realize
