### ISSUE TITLE
main.containers.tf - An argument "update" is not expected here

### ISSUE THREAD

**Issue by chris-b-chalmers** [Azure/terraform-azurerm-avm-res-storage-storageaccount#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.8.2

### Module Version

0.1.1

### AzureRM Provider Version

3.100.0

### Affected Resource(s)/Data Source(s)

azapi_resource

### Terraform Configuration Files

```hcl
providers.tf

provider "azurerm" {
    features {}
    tenant_id       = ""
    subscription_id = ""
}

base.tf

resource "azurerm_resource_group" "example" {
    name     = "rg-storage-account-example"
    location = "UK South"
}

resource.tf

module "example" {
    source              = "git::https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount"
    resource_group_name = azurerm_resource_group.example.name
    location            = azurerm_resource_group.example.location
    name                = "saccuksupdatebug"
}

versions.tf

terraform {
  required_version = "1.8.2"

  required_providers {
    azurerm = ">= 3.100.0"
  }
}
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/example/main.containers.tf line 21, in resource "azapi_resource" "containers":
│   21:       update = timeouts.value.update
│ 
│ An argument named "update" is not expected here.
╵
```

### Expected Behaviour

Terraform plan succeeds

### Actual Behaviour

Terraform plan fails

### Steps to Reproduce

terraform init
terraform plan

### References

https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource has create, read, and delete but not an update entry

When removing "update = timeouts.value.update" (line 21) from main.containers.tf there is no error

**Comment by JoshuaMcConnaughey** [comment]
This appears to be related to terraform provider azapi version 1.13.0, which was published 2 days ago. If I back down to version 1.12.0, there is no error.

**Comment by chris-b-chalmers** [comment]
Confirmed above. 

With versions.tf to specify the older version it works

terraform {
  required_version = "1.8.2"

  required_providers {
    azurerm = ">= 3.100.0"
    azapi = {
      source = "azure/azapi"
      version = "1.12.0"
    }
  }
}

**Comment by chinthakaru** [comment]
Sorry for the delayed update; we have temporarily removed the update argument until it becomes available in a future release. Code is working again.

**Comment by chinthakaru** [comment]
This has been fixed with the removal of the update argument.
