### ISSUE TITLE
Output for resource.azurerm_storage_share.this missing

### ISSUE THREAD

**Issue by mathiasjespers** [Azure/terraform-azurerm-avm-res-storage-storageaccount#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The resource.azurerm_storage_share.this does not get outputted in the module. This is weird considering both tables and queues do get outputted.

### New or Affected Resource(s)/Data Source(s)

resource "azurerm_storage_share" "this"

### Potential Terraform Configuration

```hcl
output "shares" {
  description = "Map of storage shares that are created."
  value = {
    for name, share in azurerm_storage_share.this :
    name => {
      id                   = share.id
      name                 = share.name
      storage_account_name = share.storage_account_name
      access_tier          = share.access_tier
      enabled_protocol     = share.enabled_protocol
      metadata             = share.metadata
    }
  }
}
```

**Comment by chinthakaru** [comment]
Module has been updated with PR #108.
