### ISSUE TITLE
Support for sending diagnostics to event hubs

### ISSUE THREAD

**Issue by digorgonzola** [Azure/terraform-azurerm-avm-res-storage-storageaccount#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current implementation of the `azurerm_monitor_diagnostic_setting` resource does not support sending events to an event hub.

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_diagnostic_setting" "this" {
  for_each = var.diagnostic_settings

  name                           = each.value.name != null ? each.value.name : "diag-${var.name}"
  target_resource_id             = azurerm_key_vault.this.id
  eventhub_authorization_rule_id = each.value.event_hub_authorization_rule_resource_id
  eventhub_name                  = each.value.event_hub_name
  log_analytics_destination_type = each.value.log_analytics_destination_type
  log_analytics_workspace_id     = each.value.workspace_resource_id
  partner_solution_id            = each.value.marketplace_partner_resource_id
  storage_account_id             = each.value.storage_account_resource_id

  dynamic "enabled_log" {
    for_each = each.value.log_categories
    content {
      category = enabled_log.value
    }
  }
  dynamic "enabled_log" {
    for_each = each.value.log_groups
    content {
      category_group = enabled_log.value
    }
  }
  dynamic "metric" {
    for_each = each.value.metric_categories
    content {
      category = metric.value
    }
  }
}
```

**Comment by digorgonzola** [comment]
Looking more closely at this, it appears to be an oversight in resource blocks as the `variables-diagnostics.tf` file has the input parameter for event hubs: https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/blob/da400b1482f64f7b352b16b1bb10fcaa92119464/variables.diagnostics.tf#L12

**Comment by digorgonzola** [comment]
@chinthakaru I'd be happy to create a PR for this.

**Comment by chinthakaru** [comment]
@digorgonzola Thanks a lot for the interest to create a PR on this. But this has been developed in a another branch and waiting to deploy soon.

**Comment by chinthakaru** [comment]
Event Hub supportability has been added to the module and this issue should be resolved.
